# Generated by Django 5.1.6 on 2025-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='place_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
