# Generated by Django 5.1.6 on 2025-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadphoto', '0003_referencephoto_userphoto_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
